I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 31, in script call
    call intro2 from _call_intro2
  File "game/intro2.rpy", line 252, in script
    show pluto shy with dissolve(0.2)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 31, in script call
    call intro2 from _call_intro2
  File "game/intro2.rpy", line 252, in script
    show pluto shy with dissolve(0.2)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\ast.py", line 1658, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\exports.py", line 1657, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\core.py", line 2798, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\core.py", line 3752, in interact_core
    trans = self.ongoing_transition[None](
TypeError: 'Dissolve' object is not callable

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Planetary Pursuits ver.0.2
Wed May  3 00:42:11 2023
