I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "renpy/common/00start.rpy", line 190, in <module>
    renpy.execute_default_statement(True)
  File "game/day0.rpy", line 2, in set_default
    default menu2_choice = false
  File "game/day0.rpy", line 2, in <module>
    default menu2_choice = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 190, in <module>
    renpy.execute_default_statement(True)
  File "renpy/exports.py", line 3753, in execute_default_statement
    i.set_default(start)
  File "game/day0.rpy", line 2, in set_default
    default menu2_choice = false
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/day0.rpy", line 2, in <module>
    default menu2_choice = false
NameError: name 'false' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Planetary Pursuits 1.0
Tue Nov  1 01:46:24 2022
