I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 55, in script call
    call intro1
  File "game/intro1.rpy", line 187, in script call
    call intro2
  File "game/intro2.rpy", line 65, in script
    menu:
  File "game/intro2.rpy", line 66, in <module>
    "\"Any specific way I should handle things?\"" if not already_asked_1:
NameError: name 'already_asked_1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 55, in script call
    call intro1
  File "game/intro1.rpy", line 187, in script call
    call intro2
  File "game/intro2.rpy", line 65, in script
    menu:
  File "renpy/ast.py", line 1688, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "renpy/exports.py", line 1026, in menu
    condition = renpy.python.py_eval(condition)
  File "renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/intro2.rpy", line 66, in <module>
    "\"Any specific way I should handle things?\"" if not already_asked_1:
NameError: name 'already_asked_1' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Planetary Pursuits 1.0
Sun Nov 27 20:14:44 2022
