I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 32, in script call
    call pluto_date1 from _call_pluto_date1
  File "game/pluto_date1.rpy", line 421, in script
    $ renpy.sound.stop(fadeout-0.5)
  File "game/pluto_date1.rpy", line 421, in <module>
    $ renpy.sound.stop(fadeout-0.5)
NameError: name 'fadeout' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 32, in script call
    call pluto_date1 from _call_pluto_date1
  File "game/pluto_date1.rpy", line 421, in script
    $ renpy.sound.stop(fadeout-0.5)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/pluto_date1.rpy", line 421, in <module>
    $ renpy.sound.stop(fadeout-0.5)
NameError: name 'fadeout' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Planetary Pursuits ver.0.2
Tue May  2 01:36:52 2023
